<html>
<head>
<title>facebook login page</title>
</head>
<body>
<form action="page.php" METHOD=GET>
<li>email<br><input type="text"name="email"></li>
<li>password<br><input type="hidden" name="password" value="aayushi"><br><a href="">forgotten account?</a></li>
<li><input type="submit" name="login" value="login"></li>
<li><input type="submit" name="reset" value="reset"></li>
</form>
</body>
</html>