<html>
<?php
echo"aayushi <br/>";
echo"OPERATORS <br/>";
echo"RELATIONAL OPERATORS <br/>";
echo"LESS THEN <br/>";
$a=10;
$b=20;
if($a<$b)
{
	echo"the variable a is less than b <br/>";
}
else
{
echo"the variable b is less than a <br/>";
}
echo"GREATER THAN <br/>";
if($a>$b)
{
	echo"the variable a is greater than b <br/>";
}
else
{
echo"the variable b is greater than a <br/>";
}
echo"LESS THAN EQUAL TO <br/>";
if($a<=$b)
{
	echo"the variable a is less than equal to b <br/>";
}
else
{
echo"the variable a is not less than equal to <br/>";
}
echo"GREATER THAN EQUAL TO <br/>";
if($a>=$b)
{
	echo"the variable a is greater than equal to b <br/>";
}
else
{
echo"the variable b is greater than equal to a <br/>";
}
echo"EQUAL TO <br/>";
if($a==$b)
{
	echo"the variable a is equal to b <br/>";
}
else
{
echo"the variable a is not equal to b <br/>";
}
?>
</html>